app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, FloatField, PasswordField, \
                    DateTimeField
from wtforms.validators import DataRequired, EqualTo
from datetime import datetime, timedelta

dia_anterior = datetime.utcnow() - timedelta(days=1)

class CotaForm(FlaskForm):
    dt = DateField('Data da cotação', validators=[DataRequired()], render_kw={'placeholder': "Formato: " + dia_anterior.strftime('%Y-%m-%d')})
    submit = SubmitField('Enviar')

class EditarCotacaoForm(FlaskForm):
    dt = StringField('Data do cadastro', validators=[DataRequired()])
    abertura = FloatField('Valor de abertura', validators=[DataRequired()])
    maximo = FloatField('Valor máximo', validators=[DataRequired()]) 
    minimo = FloatField('Valor mínimo', validators=[DataRequired()]) 
    fechamento = FloatField('Valor de fechamento', validators=[DataRequired()]) 
    volume = FloatField('Volume', validators=[DataRequired()]) 

    submit = SubmitField('Enviar')

class EmpresaForm(FlaskForm):
    sigla = StringField('sigla da empresa', validators=[DataRequired()])
    submit = SubmitField('Enviar')

class EditarEmpresaForm(FlaskForm):
    nome = StringField('Nome da empresa', validators=[DataRequired()])
    simbolo = StringField('Símbolo da empresa', validators=[DataRequired()] )
    regiao = StringField('Região', validators=[DataRequired()])
    tipo =StringField('Tipo', validators=[DataRequired()]) 
    abertura =StringField('Abertura', validators=[DataRequired()]) 
    fechamento =StringField('Fechamento', validators=[DataRequired()]) 
    zona =StringField('Zona', validators=[DataRequired()]) 
    moeda =StringField('Moeda', validators=[DataRequired()]) 
    submit = SubmitField('Enviar')

class UsuarioForm(FlaskForm):
    """
    Form para editar configurações do usuário
    """
    nome = StringField('Nome', validators=[DataRequired()])
    sobrenome = StringField('Sobrenome', validators=[DataRequired()])
    password = PasswordField('Senha', validators=[EqualTo('confirm_password')])
    confirm_password = PasswordField('Confirme a senha')
    submit = SubmitField('Cadastrar')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, render_template, redirect, \
     url_for, flash, request, current_app, jsonify
from flask_login import current_user, login_required
from config import Config
from . import home
from app import db
import requests, json
from .forms import CotaForm, EditarCotacaoForm, EmpresaForm, EditarEmpresaForm, UsuarioForm
from app.models import Cotacao, Empresa, Usuario
from datetime import datetime

@home.route('/')
def homepage():
    """
    Rende o template na rota /
    """
    return render_template('home/index.html', 
                            title="Bem vindo!")

@home.route('/painel')
@login_required
def painel():
    """
    Rende o painel na rota /painel
    """
    return render_template('home/painel.html', title="Painel")

@home.route('/cotacoes', methods=['GET', 'POST'])
@login_required
def listar_cotacoes():
    page = request.args.get('page', 1, type=int)

    cotacoes = Cotacao.query.order_by(Cotacao.data_cadastro_string.desc()).paginate(
            page, current_app.config['CPP'], False)

    next_url = url_for('home.listar_cotacoes', page=cotacoes.next_num)\
            if cotacoes.has_next else None
    prev_url = url_for('home.listar_cotacoes', page=cotacoes.prev_num)\
            if cotacoes.has_prev else None

    return render_template('home/cotacoes.html',
                           cotacoes=cotacoes.items, 
                           title="Cotações",
                           next_url=next_url,
                           prev_url=prev_url)



@home.route('/cotacoes/cadastrar', methods=['GET', 'POST'])
@login_required
def cadastrar_cotacao():
    cadastrando_cotacao = True
    form = CotaForm()
    if form.validate_on_submit():
        cot = requests.get('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=BOVA11.SAO&apikey=0ED3YY5RQSO6UILH').json()
        cot = cot['Time Series (Daily)'][str(form.dt.data)]
        cotacoes = Cotacao(
            abertura=cot['1. open'],
            data_consulta=form.dt.data,
            maximo=cot['2. high'],
            minimo=cot['3. low'],
            fechamento=cot['4. close'],
            volume=cot['5. volume']
        )
        db.session.add(cotacoes)
        db.session.commit()
        
        flash('Cotação cadastrada com sucesso!')
        return redirect(url_for('home.listar_cotacoes'))

    return render_template("home/cotacao.html", title="Cotações", form=form)

@home.route('/cotacoes/editar/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_cotacao(id):
    """
    Edita uma cotação diretamente do bd 
    """
    cadastrando_cotacao = False

    cotacao = Cotacao.query.get_or_404(id)
    form = EditarCotacaoForm(obj=cotacao)

    if form.validate_on_submit():
        cotacao.data_cadastro = datetime.strptime(form.dt.data, '%d-%m-%Y')
        cotacao.abertura = form.abertura.data
        cotacao.maximo = form.maximo.data
        cotacao.minimo = form.minimo.data
        cotacao.fechamento = form.fechamento.data
        cotacao.volume = form.volume.data
        db.session.commit()
        flash('Cotação editada com sucesso!')

        return redirect(url_for('home.listar_cotacoes'))

    form.dt.data = cotacao.data_cadastro.strftime("%d-%m-%Y")
    form.abertura.data = cotacao.abertura 
    form.maximo.data = cotacao.maximo
    form.minimo.data = cotacao.minimo
    form.fechamento.data = cotacao.fechamento
    form.volume.data = cotacao.volume


    return render_template('home/cotacao.html', action="Edit",
                           cadastrando_cotacao=cadastrando_cotacao, form=form,
                           cotacao=cotacao, title="Editar cotação")

@home.route('/cotacoes/deletar/<int:id>', methods=['GET', 'POST'])
@login_required
def deletar_cotacao(id):
    """
    Deleta uma cotação do banco de dados
    """
    cotacao = Cotacao.query.get_or_404(id)
    
    db.session.delete(cotacao)
    db.session.commit()
    flash('Cotação deletada com sucesso.')

    # redirect to the departments page
    return redirect(url_for('home.listar_cotacoes'))

@home.route('/empresas', methods=['GET', 'POST'])
@login_required
def listar_empresas():
    page = request.args.get('page', 1, type=int)

    empresas = Empresa.query.order_by(Empresa.nome).paginate(
            page, current_app.config['CPP'], False)

    next_url = url_for('home.listar_empresas', page=empresas.next_num)\
            if empresas.has_next else None
    prev_url = url_for('home.listar_empresas', page=empresas.prev_num)\
            if empresas.has_prev else None

    return render_template('home/empresas.html',
                           empresas=empresas.items, 
                           title="Empresas",
                           next_url=next_url,
                           prev_url=prev_url)
        
@home.route('/empresas/cadastrar', methods=['GET', 'POST'])
@login_required
def cadastrar_empresa():
    form = EmpresaForm()
    if form.validate_on_submit():
        try:
            emp = requests.get('https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords='+ form.sigla.data +'&apikey=0ED3YY5RQSO6UILH').json()
            emp = emp['bestMatches'][0]
        except:
                flash('Nome de empresa inválida! Tente novamente.')
                return redirect(url_for('home.cadastrar_empresa'))
        empresa = Empresa(
            nome=emp['2. name'],
            simbolo=emp['1. symbol'],
            tipo=emp['3. type'],
            regiao=emp['4. region'],
            abertura=emp['5. marketOpen'],
            fechamento=emp['6. marketClose'],
            zona=emp['7. timezone'],
            moeda=emp['8. currency']
        )
        db.session.add(empresa)
        db.session.commit()
        flash('Empresa cadastrada com sucesso!')

        return redirect(url_for('home.listar_empresas'))
    return render_template('home/empresa.html', title="Cadastrar empresa", form=form)

@home.route('/empresas/editar/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_empresa(id):
    """
    Edita uma empresa diretamente do bd 
    """
    cadastrando_empresa = False

    empresa = Empresa.query.get_or_404(id)
    form = EditarEmpresaForm(obj=empresa)

    if form.validate_on_submit():
        empresa.nome = form.nome.data
        empresa.simbolo = form.simbolo.data
        empresa.regiao = form.regiao.data
        empresa.tipo = form.tipo.data
        empresa.abertura = form.abertura.data
        empresa.fechamento = form.fechamento.data
        empresa.zona = form.zona.data
        empresa.moeda = form.moeda.data
        db.session.commit()
        flash('Empresa editada com sucesso!')

        return redirect(url_for('home.listar_empresas'))

    form.nome.data = empresa.nome
    form.simbolo.data = empresa.abertura 
    form.regiao.data = empresa.regiao
    form.tipo.data = empresa.tipo
    form.abertura = empresa.abertura
    form.fechamento = empresa.fechamento
    form.zona.data = empresa.zona
    form.moeda.data = empresa.moeda


    return render_template('home/empresa.html', action="Edit",
                           cadastrando_empresa=cadastrando_empresa, form=form,
                           empresa=empresa, title="Editar empresa")

@home.route('/empresas/deletar/<int:id>', methods=['GET', 'POST'])
@login_required
def deletar_empresa(id):
    """
    Deleta uma empresa do banco de dados
    """
    empresa = Empresa.query.get_or_404(id)
    
    db.session.delete(empresa)
    db.session.commit()
    flash('Empresa deletada com sucesso.')

    return redirect(url_for('home.listar_empresas'))

@home.route('/usuarios', methods=['GET', 'POST'])
@login_required
def listar_usuarios():

    usuarios = Usuario.query.all()

    return render_template('home/usuarios/usuarios.html',
                           usuarios=usuarios, title="Usuaários")



@home.route('/usuarios/editar/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_usuarios(id):

    add_usuario = False

    usuario = Usuario.query.get_or_404(id)
    form = UsuarioForm(obj=usuario)
    if form.validate_on_submit():
        usuario.nome = form.nome.data
        usuario.sobrenome = form.sobrenome.data
        usuario.password = form.password.data
        db.session.add(usuario)
        db.session.commit()
        flash('Usuário editado com sucesso!')


        return redirect(url_for('home.listar_usuarios'))

    form.nome.data = usuario.nome

    return render_template('home/usuarios/usuario.html', action="Editar",
                           add_usuario=add_usuario, form=form,
                           usuario=usuario, title="Editar Usuário")


@home.route('/usuarios/deletar/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_usuario(id):

    usuario = Usuario.query.get_or_404(id)
    db.session.delete(usuario)
    db.session.commit()
    flash('Funcionário deletado com sucesso!')

    return redirect(url_for('home.listar_usuarios'))

app/templates/home/cotacao.html
<!-- app/templates/home/cotacao.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Cotações{% endblock %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center">
    <h1>Cadastrar cotação com base em data</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/home/cotacoes.html
<!-- app/templates/home/cotacoes.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Cotações{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Cotações</h1>
        {% if cotacoes %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th> Data de cadastro </th>
                  <th> Data de consulta </th>
                  <th> Valor de Abertura </th>
                  <th> Valor máximo </th>
                  <th> Valor mínimo </th>
                  <th> Valor de fechamento </th>
                  <th> Volume </th>
                  <th> Editar </th>
                  <th> Deletar </th>
                </tr>
              </thead>
              <tbody>
              {% for cotacao in cotacoes %}
                <tr>
                  <td> {{ cotacao.data_cadastro.strftime('%d-%m-%Y') }} </td>
                  <td> {{ cotacao.data_consulta.strftime('%d-%m-%Y')}} </td>
                  <td> {{ cotacao.abertura }} </td>
                  <td> {{ cotacao.maximo }} </td>
                  <td> {{ cotacao.minimo }} </td>
                  <td> {{ cotacao.fechamento}} </td>
                  <td> {{ cotacao.volume }} </td>
                  <td>
                    <a href="{{ url_for('home.editar_cotacao', id=cotacao.id) }}">
                      <i class="fa fa-pencil"></i> Editar 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('home.deletar_cotacao', id=cotacao.id) }}">
                      <i class="fa fa-trash"></i> Deletar 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> Nenhuma Cotação cadastrada. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('home.cadastrar_cotacao') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Cadastrar cotação
          </a>
    		<nav aria-label="...">
        		<ul class="pager">
            		<li class="previous{% if not prev_url %} disabled{% endif %}">
                		<a href="{{ prev_url or '#' }}">
                    		<span aria-hidden="true">&larr;</span> {{
							('Cotações recentes') }}
                		</a>
            		</li>
            		<li class="next{% if not next_url %} disabled{% endif %}">
                		<a href="{{ next_url or '#' }}">
                    		{{ ('Cotações antigas') }} <span aria-hidden="true">&rarr;</span>
                		</a>
            		</li>
        		</ul>
    		</nav>
		  </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/empresa.html
<!-- app/templates/home/cotacao.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Empresas{% endblock %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center">
    <h1>Cadastrar empresa com base em sigla</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/home/empresas.html
<!-- app/templates/home/cotacoes.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Empresas{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Empresas</h1>
        {% if empresas %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th> Nome </th>
                  <th> Símbolo </th>
                  <th> Tipo </th>
                  <th> Região </th>
                  <th> Abertura </th>
                  <th> Fechamento </th>
                  <th> Zona UTC </th>
                  <th> Editar </th>
                  <th> Deletar </th>
                </tr>
              </thead>
              <tbody>
              {% for empresa in empresas %}
                <tr>
                  <td> {{ empresa.nome }} </td>
                  <td> {{ empresa.simbolo }} </td>
                  <td> {{ empresa.tipo }} </td>
                  <td> {{ empresa.regiao }} </td>
                  <td> {{ empresa.abertura}} </td>
                  <td> {{ empresa.fechamento }} </td>
                  <td> {{ empresa.zona }} </td>
                  <td>
                    <a href="{{ url_for('home.editar_empresa', id=empresa.id) }}">
                      <i class="fa fa-pencil"></i> Editar 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('home.deletar_empresa', id=empresa.id) }}">
                      <i class="fa fa-trash"></i> Deletar 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> Nenhuma empresa cadastrada. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('home.cadastrar_empresa') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Cadastrar empresa
          </a>
    		<nav aria-label="...">
        		<ul class="pager">
            		<li class="previous{% if not prev_url %} disabled{% endif %}">
                		<a href="{{ prev_url or '#' }}">
                    		<span aria-hidden="true">&larr;</span> {{
							('Empresas recentes') }}
                		</a>
            		</li>
            		<li class="next{% if not next_url %} disabled{% endif %}">
                		<a href="{{ next_url or '#' }}">
                    		{{ ('Empresas antigas') }} <span aria-hidden="true">&rarr;</span>
                		</a>
            		</li>
        		</ul>
    		</nav>
		  </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>PontoTel</h1>
                    <h3>Consumindo a API Alphavantage!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/painel.html
<!-- app/templates/home/painel.html -->

{% extends "base.html" %}
{% block title %}Painel{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Painel</h1>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
						{% if current_user.is_authenticated %}
							<li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
    					{% else %}
                        	<li><a href="#">Cadastrar</a></li>
                        	<li class="footer-menu-divider">⋅</li>
                        	<li><a href="#">Login</a></li>
						{% endif %}
                    </ul>
                    <p class="copyright text-muted small">Copyright © 2019. All Rights Reserved</p>
                </div>
            </div>
        </div>
	{% endblock %}